field: f387678b-4bf0-44d0-9c69-1d60c3f3f47f # Recipe Ingredients
fieldLayouts:
  4ff942a1-a358-4d9f-b7ea-953cbbfcd796:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c468e7d7-2de4-4f6e-9a17-a3f6b7db6201 # Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32fd2e9a-00c0-4af0-9375-1f7c17d98e7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85a72c78-c803-474c-84f0-fdc1af1facd0 # Unit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b711e58d-36da-42b1-95e0-f378fc9f3c15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3831c4c6-1e3f-42ff-99f7-5e4eed6b7ae3 # Ingredient
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50d40cc6-b13d-4e77-909f-a030c360f6af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2718b8a-1bf7-4c78-8ed1-bd2d973a6e61 # Optional
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c42c4455-0726-4f91-a9dd-57883ac41781
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b1e2702-abce-4b2c-b692-58a2812a05fa
        userCondition: null
fields:
  85a72c78-c803-474c-84f0-fdc1af1facd0: # Unit
    columnSuffix: avvrcadt
    contentColumnType: string(11)
    fieldGroup: null
    handle: unit
    instructions: null
    name: Unit
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Single
            -
              - value
              - single
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Grams
            -
              - value
              - grams
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tablespoons
            -
              - value
              - tablespoons
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Teaspoons
            -
              - value
              - teaspoons
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  3831c4c6-1e3f-42ff-99f7-5e4eed6b7ae3: # Ingredient
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ingredient
    instructions: null
    name: Ingredient
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:842cdeba-cd27-4e0b-9de5-60ed051ee6bd' # Ingredients
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  c468e7d7-2de4-4f6e-9a17-a3f6b7db6201: # Amount
    columnSuffix: agrmetjb
    contentColumnType: integer(10)
    fieldGroup: null
    handle: amount
    instructions: null
    name: Amount
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  d2718b8a-1bf7-4c78-8ed1-bd2d973a6e61: # Optional
    columnSuffix: apfpjfko
    contentColumnType: boolean
    fieldGroup: null
    handle: optional
    instructions: 'Whether this is an optional ingredient in the recipe.'
    name: Optional
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: ingredient
name: Ingredient
sortOrder: 1
