fieldLayouts:
  85693f11-7ff0-4592-af59-550353e07dc5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0dea6460-8e88-4f92-bfcd-c47dbded964e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9607b25c-41e6-49ee-92f6-4f598d9bb638 # Image
            instructions: null
            label: Icon
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ed4b740-164d-438a-a1dc-3943ce2a3161
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4455e8f9-3d20-4764-a87b-5177d121b07e # Summary
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efa13d8e-1daa-4762-9330-fb054c554447
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3fc59463-95a7-4791-9a31-a49c404793cf
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 4f4c5e55-bdb6-4b11-a80c-a707a67c93c8 # Dietary Preferences
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
