fieldLayouts:
  c2f2eebe-5898-4db6-bc94-7f830f92797a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b5fde786-34ca-42d1-ba97-f38842ff1c7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9607b25c-41e6-49ee-92f6-4f598d9bb638 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68ac6485-8fd6-43a4-95ab-856db69f7302
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4455e8f9-3d20-4764-a87b-5177d121b07e # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b354eb90-cb33-4cac-bb97-3d36e37ad629
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 224accbf-3cca-418d-aa29-0c687d64c134
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 842cdeba-cd27-4e0b-9de5-60ed051ee6bd # Ingredients
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
