columnSuffix: null
contentColumnType: string
fieldGroup: 25f0b070-8223-43e7-a9d6-f30e124aefba # Trips
handle: countries
instructions: null
name: Countries
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Add a country'
  showSiteMenu: false
  sources:
    - 'section:65e19c67-6869-4b02-8f73-1faddec1820b' # Countries
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
