columnSuffix: null
handle: ingredient
instructions: null
name: 'Recipe Ingredients - Ingredient - Ingredient'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:842cdeba-cd27-4e0b-9de5-60ed051ee6bd' # Ingredients
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
