columnSuffix: null
contentColumnType: string
fieldGroup: 2f80283d-6b98-4fda-8513-85293feafacf # Food
handle: instructionSteps
instructions: 'Add one instructions step per block.'
name: 'Instruction Steps'
searchable: false
settings:
  contentTable: '{{%matrixcontent_instructionsteps}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
