columnSuffix: null
contentColumnType: string
handle: instructionSteps
instructions: 'Add one instructions step per block.'
name: 'Instruction Steps'
searchable: false
settings:
  entryTypes:
    - 2ff70388-58ff-42cc-b63c-8b6a921ff80a
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
