columnSuffix: yxrtmvkq
handle: levelOfDifficulty
instructions: null
name: 'Level of Difficulty'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Easy
        -
          - value
          - easy
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - medium
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Difficult
        -
          - value
          - difficult
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
