columnSuffix: pjqnujfz
handle: numberOfServings
instructions: 'The number of people this recipe serves.'
name: 'Number of Servings'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: servings
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
