columnSuffix: brpygnsi
contentColumnType: integer(10)
fieldGroup: 2f80283d-6b98-4fda-8513-85293feafacf # Food
handle: preparationTime
instructions: null
name: 'Preparation Time'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
