columnSuffix: pjurfwul
handle: preparationTimeUnits
instructions: null
name: 'Preparation Time Units'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Minutes
        -
          - value
          - minutes
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Hours
        -
          - value
          - hours
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Days
        -
          - value
          - days
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
