columnSuffix: null
contentColumnType: string
handle: recipeIngredients
instructions: null
name: 'Recipe Ingredients'
searchable: false
settings:
  entryTypes:
    - 350d3b36-f9ac-4a5c-9324-598b3fc4d31f
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
