columnSuffix: null
contentColumnType: string
fieldGroup: 2f80283d-6b98-4fda-8513-85293feafacf # Food
handle: recipeIngredients
instructions: null
name: 'Recipe Ingredients'
searchable: false
settings:
  contentTable: '{{%matrixcontent_recipeingredients}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
