columnSuffix: wbpwyepw
contentColumnType: boolean
handle: suitableForChildren
instructions: 'Whether this recipe is suitable for preparing with children.'
name: 'Suitable for Children'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
