columnSuffix: avvrcadt
handle: unit
instructions: null
name: 'Recipe Ingredients - Ingredient - Unit'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Single
        -
          - value
          - single
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Grams
        -
          - value
          - grams
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Tablespoons
        -
          - value
          - tablespoons
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Teaspoons
        -
          - value
          - teaspoons
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
