defaultPlacement: end
enableVersioning: true
entryTypes:
  - 65a39f0b-19b3-4457-b8da-8bd66251a3b9 # Countries
handle: countries
maxAuthors: 1
name: Countries
propagationMethod: all
siteSettings:
  658815bf-b62b-4167-b965-8343a311b9f3: # COS
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
