defaultPlacement: end
enableVersioning: true
handle: dietaryPreferences
name: 'Dietary Preferences'
propagationMethod: all
siteSettings:
  658815bf-b62b-4167-b965-8343a311b9f3: # COS
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
