defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7d0487ea-cc61-4615-bbec-1d35fb6e0129 # Dietary Preferences
handle: dietaryPreferences
maxAuthors: 1
name: 'Dietary Preferences'
propagationMethod: all
siteSettings:
  658815bf-b62b-4167-b965-8343a311b9f3: # COS
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
