defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8343f4ab-c5bd-42a0-a37e-3c58121f759a # Recipes - Default
handle: recipes
maxAuthors: 1
name: Recipes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  658815bf-b62b-4167-b965-8343a311b9f3: # COS
    enabledByDefault: true
    hasUrls: true
    template: recipe.twig
    uriFormat: 'recipes/{slug}'
type: channel
